theme = "b"

[editor]
line-number = "relative"
mouse = false
bufferline = "multiple"

[editor.soft-wrap]
enable = true

[editor.lsp]
display-inlay-hints = true

[keys.insert]
j = { k = "normal_mode" }
